Lp27 dev 4 minimum bd and calss models
kosmonavtus/lp_vault_bot_storage pull request #1
Opened 2022-12-24 08:10 UTC by kosmonavtus

2022-12-26 05:43 UTC, Melevir requested changes

2022-12-26 05:43 UTC, Melevir commented on app.py
> +def hello_world():
Этот урл можно смело удалить.

2022-12-26 05:43 UTC, Melevir commented on app.py
> +@app.route("/get_uers", methods=['GET'])
get_ в урле лишний, для этого есть хттп-глагол.

2022-12-26 05:43 UTC, Melevir commented on app.py
> +@app.route("/get_secret", methods=['GET'])
И тут лишний get

2022-12-26 05:43 UTC, Melevir commented on app.py
> +    user_id = request.args.get('user_id')
Нет обработки случая отсутствия параметра

2022-12-26 05:43 UTC, Melevir commented on app.py
> +    secret_id = request.args.get('secret_id')
И тут не обрабатывается случай отсутствия параметра

2022-12-26 05:43 UTC, Melevir commented on app.py
> +    return AppSecert.get_secrt(secret_id)
get_secrt – опечатка

2022-12-26 05:43 UTC, Melevir commented on app.py
> +app.run(debug=True)
Такой код надо прятать за if name main

2022-12-26 05:43 UTC, Melevir commented on classes.py
> +from model import Users, Secrets
Название модуля не говорит ничего о том, что в нём, переименовать бы.

2022-12-26 05:43 UTC, Melevir commented on classes.py
> +        self.sycret_type = sycret_type
Чтобы не писать такой код руками, используй датаклассы.

И прочекай весь код на опечатки :)

2022-12-26 05:43 UTC, Melevir commented on classes.py
> +                        name=self.name,
Много лишних отступов

2022-12-26 05:43 UTC, Melevir commented on classes.py
> +        for _ in q_result:
Лишний цикл for, неправильно названа переменная, лишняя эф-строка

2022-12-26 05:43 UTC, Melevir commented on classes.py
> +if __name__ == "__main__":
Удаляй весь иф с содержимым раз он не нужен.

2022-12-26 05:43 UTC, Melevir commented on generate_data.py
> +from faker import Faker
Не вижу добавления этого модуля в requirements в этом пр.

2022-12-26 05:43 UTC, Melevir commented on generate_data.py
> +    #INSERT INTO secret_type(name, sycret_store_type) VALUES (login_password, 1);
Опять закомментированный код.

2022-12-26 05:43 UTC, Melevir commented on model.py
> +# Для логин / паролей одни, для RSA другие, для SSL X.509 третие.
Непонятно, зачем принимать такое странное решение. Давай пока будем использовать одну таблицу

2022-12-26 05:43 UTC, Melevir commented on model.py
> +class Secret_type(Base):
Классы принято назвать КемелКейсом

2022-12-26 05:43 UTC, Melevir commented on settings.py
> +CONNECTION_STRING = 'postgresql://vault_pass_user:daevahg2uoFeoguthei9Ainai1faad1G@localhost:55000/vault_bot'
Кажется, этого не должно быть в репо.

2022-12-26 05:43 UTC, Melevir commented on settings.py
> +CONNECTION_STRING = 'postgresql://vault_pass_user:daevahg2uoFeoguthei9Ainai1faad1G@localhost:55000/vault_bot'
Ещё ставь пустую строку в конце всех файлов, тогда не будет этих красных знаков на гитхабе и дифф будет выглядеть лучше когда новые строки добавишь в существующий файл.

2023-01-03 13:02 UTC, kosmonavtus commented on app.py
> +def hello_world():
ok

2023-01-03 13:02 UTC, kosmonavtus commented on app.py
> +@app.route("/get_uers", methods=['GET'])
ok

2023-01-03 13:02 UTC, kosmonavtus commented on app.py
> +@app.route("/get_secret", methods=['GET'])
ok

2023-01-03 13:03 UTC, kosmonavtus commented on app.py
> +    secret_id = request.args.get('secret_id')
И тут переделал, и. тоже доработаю.

2023-01-03 13:03 UTC, kosmonavtus commented on generate_data.py
> +from faker import Faker
fix it

2023-01-03 13:03 UTC, kosmonavtus commented on generate_data.py
> +    #INSERT INTO secret_type(name, sycret_store_type) VALUES (login_password, 1);
fix it

2023-01-03 13:03 UTC, kosmonavtus commented on model.py
> +# Для логин / паролей одни, для RSA другие, для SSL X.509 третие.
пока забил на него

2023-01-03 13:03 UTC, kosmonavtus commented on model.py
> +class Secret_type(Base):
fix it

2023-01-03 13:04 UTC, kosmonavtus commented on settings.py
> +CONNECTION_STRING = 'postgresql://vault_pass_user:daevahg2uoFeoguthei9Ainai1faad1G@localhost:55000/vault_bot'
fix it переделал на toml

2023-01-03 13:50 UTC, Melevir commented on README.md
> +
За ридми лайкос

2023-01-03 13:50 UTC, Melevir commented on app/__init__.py
> +#from werkzeug.exceptions import BadRequestKeyError
Это всё не стесняйся удалять, в гите делать ему нечего.

2023-01-03 13:50 UTC, Melevir commented on app/classes.py
> +# Есть ли какоето соглашение которое говорит модуль с исключениями называем "вот так"?.
Только тык: документация, сорцы, всё такое. 

Я пользуюсь автоимпортом в пайчарме: он ищет сущноть с указанным именем в установленных пакетах.

2023-01-03 13:50 UTC, Melevir commented on app/classes.py
> +    def get_secret(self, secret_id: int) -> str:
Тут у тебя метод возвращает или секрет или ошибку и ты не сможешь достоверно сказать, что именно. Лучше так не делать.

2023-01-03 13:50 UTC, Melevir commented on app/classes.py
> +        # Как то можно это во что то "завернуть" чтобы не дублировать?
except умеет принимать на вход несколько исключений. А мессадж для конкретного исключения уже можно сформировать отдельно.

2023-01-03 13:50 UTC, Melevir commented on app/classes.py
> +class AppUsers:
Тут и выше дата-класс бы использовать

2023-01-03 13:50 UTC, Melevir commented on app/classes.py
> +                    password=self.password
С отступами беда

2023-01-03 13:50 UTC, Melevir commented on app/classes.py
> +        #  А не "взрывавалась" в случае ошибки.
Самый простой способ – возвращать объект, у которого есть поля типа с самим секретом, успешно ли его доставание, какая ошибка и тд

2023-01-03 13:50 UTC, Melevir commented on app/classes.py
> +            # А както с ORM но без лишнго селекта в базу можно?
Ну да, сделать через алхимию запрос в духе delete from user where id=xxx

2023-01-03 13:50 UTC, Melevir commented on app/classes.py
> +from app.secret.models import Secrets
Название модуля не оч

2023-01-03 13:50 UTC, Melevir commented on app/db.py
> +db_session = scoped_session(sessionmaker(bind=engine))
Дело в том, что один объект сессии можно использовать только в одном потоке, а если у тебя сервис запущен в 10 потоков, то в каждом нужно создать свою сессию и в зависимости от потома использовать нужную.

Вот это scoped_session и делает

2023-01-03 13:50 UTC, Melevir commented on app/db_model.py
> +class login_password(Base):
Много пустых строк и название не КемелКейсом

2023-01-03 13:50 UTC, Melevir commented on app/db_model.py
> +    sycret_store_type = Column(Integer, ForeignKey("secret_type.id"))
Очепятка

2023-01-03 15:24 UTC, kosmonavtus commented on app/__init__.py
> +#from werkzeug.exceptions import BadRequestKeyError
Удалил, у меня навязчивая привычка намеренно оставлять такие комментарии, ни как не избавлюсь от нее (

2023-01-03 15:24 UTC, kosmonavtus commented on app/classes.py
> +# Есть ли какоето соглашение которое говорит модуль с исключениями называем "вот так"?.
понял

2023-01-03 15:45 UTC, kosmonavtus commented on app/classes.py
> +    def get_secret(self, secret_id: int) -> str:
Переделал, возвращаю назад объект sqlalchemy.orm.query.Query, 
Это будет норм ? 

```
    @classmethod
    def get_secret(self, secret_id: int) -> orm.query.Query:
        try:
            q_result = Secrets.query.filter(Secrets.id == secret_id)
            return q_result
```

2023-01-03 15:48 UTC, kosmonavtus commented on app/classes.py
> +        # Как то можно это во что то "завернуть" чтобы не дублировать?
Не понимаю как сформировать несколько сообщений для разных в Exception внутри одного except. (

Например, было так:

```
 except (exc.DataError):
            return f'incorrect parameter secret_id: {secret_id}'
        except (exc.InternalError):
            return f'I dont understand why, but this sqlalchemy.exc.InternalError'
```


` except (exc.DataError, exc.InternalError):`
   а как тут вернуть разные меседжи на разные исключения ?

2023-01-03 15:59 UTC, kosmonavtus commented on app/classes.py
> +            # А както с ORM но без лишнго селекта в базу можно?
Пытаюсь сделать запрос типа так, 
`stmt = delete(Users).where(Users.c.id == user_id)`
вовзращает ошибку типа` type object 'Users' has no attribute 'c'%`

не понимаю почему и как правильно   ( 
уже кучу времени на это потаил (

2023-01-03 15:59 UTC, kosmonavtus commented on app/classes.py
> +from app.secret.models import Secrets
хм а как лучше назвать ?

2023-01-03 16:00 UTC, kosmonavtus commented on app/db.py
> +db_session = scoped_session(sessionmaker(bind=engine))
Понятно типа пул сессий .
Если я правильно понял то эт пул сессий

2023-01-03 16:02 UTC, kosmonavtus commented on app/db_model.py
> +class login_password(Base):
поправил

2023-01-03 16:04 UTC, kosmonavtus commented on app/db_model.py
> +    sycret_store_type = Column(Integer, ForeignKey("secret_type.id"))
secret - поправил и в базе у себя за альтерил.

2023-01-04 04:25 UTC, Melevir commented on app/classes.py
> +    def get_secret(self, secret_id: int) -> str:
Не, возвращай строку. А если что-то не так – возвращай None или выкидывай исключение.

2023-01-04 04:26 UTC, Melevir commented on app/classes.py
> +        # Как то можно это во что то "завернуть" чтобы не дублировать?
Например, так:

```
except (exc.DataError, exc.InternalError) as e:
    if isinstance(e, exc.DataError):
        ...
```

2023-01-04 04:27 UTC, Melevir commented on app/classes.py
> +            # А както с ORM но без лишнго селекта в базу можно?
Если мне не изменяет память, тебе нужен `Users.__table__`

2023-01-04 04:28 UTC, Melevir commented on app/classes.py
> +from app.secret.models import Secrets
По-умному то, что в этом модуле у тебя находится, называется repositories, например.

2023-01-06 12:07 UTC, kosmonavtus commented on app/classes.py
> +            # А както с ORM но без лишнго селекта в базу можно?
У меня закончился мануал к SQLAlchemy но в итоге мне кажется что  я разобрался как оно работает. 
Ура  @Melevir 


```
    @classmethod
    def delete_user(self, user_id: int)-> bool:
        try:
            stm = delete(Users).where(Users.id == user_id)
            db_session.execute(stm)
            db_session.commit()
            return True
        except:
            return False
```

2023-01-22 09:54 UTC, merged